### ISSUE TITLE
Other SCSS syntax highlighters fail formatOnSave check

### ISSUE THREAD

**Issue by gjjones** [dmnsgn/sublime-stylefmt#10]
Current way of checking for valid syntax hardcodes a specific syntax highlighter that does not ship by default with ST. For those of us using the Sass syntax package instead of the SCSS syntax package, this breaks autosave.

Any chance of offering a way to specify which SCSS syntax highlighter you use?

**Comment by dmnsgn** [comment]
Thanks for the PR.

**Comment by gjjones** [comment]
Thanks for the approval :)
