### ISSUE TITLE
stylelint-order not applied

### ISSUE THREAD

**Issue by owzim** [dmnsgn/sublime-stylefmt#19]
stylelint is working in sublime and the warnings are properly shown in the gutter, including the porperty order according to the following .stylellinrc I have:

```js
{
  "plugins": [
    "stylelint-order"
  ],
  "rules": {
    // ...
    "order/declaration-block-properties-specified-order": [
      "float",
      "display",
      "position",
      // ...
    ]
  }
}
```

When I run the `stylelintfmt` command, the right order is not applied though. Anything I missed?
The console spits out only the warning, that are shown in the gutter, but nothing else happens:

```json
{"line":306,"column":5,"rule":"order/declaration-block-properties-specified-order","severity":"error","text":"Expected margin-bottom to come before line-height (order/declaration-block-properties-specified-order)"}
```

**Comment by dmnsgn** [comment]
Stylefmt does not support stylelint plugins yet. It is planned to land on v6 (current version is v5) according to https://github.com/morishitter/stylefmt/issues/216#issuecomment-259831538.

In the meantime you can probably still use the [declaration-block-properties-order rule](https://github.com/stylelint/stylelint/tree/master/lib/rules/declaration-block-properties-order)

**Comment by dmnsgn** [comment]
Working since updated to stylefmt 6. Tested with:
```
{
  "plugins": [
    "stylelint-order"
  ],
  "rules": {
    "order/properties-order": [
      "padding",
      "color"
    ]
  }
}
```
