### ISSUE TITLE
Use extension for formatting

### ISSUE THREAD

**Issue by hoest** [dmnsgn/sublime-stylefmt#21]
In `scssSyntax` you need to set the name of the syntax (case-sensitive). Isn't it better to use an array of possible file extensions to match for `stylefmt`? Something like `(css|sccs|less)`...

And you can only set 1 extra syntax in `scssSyntax`,  `scssSyntax: ["Less", "Sass"]` is not possible.

**Comment by dmnsgn** [comment]
Release [5.0.0](https://github.com/dmnsgn/sublime-stylefmt/releases/tag/5.0.0) addresses this. You can now specify lists of syntaxes to be checked before checking file extensions: 

```json
{
  "formatOnSave": false,
  "syntaxes": ["SCSS", "Whatever"],
  "extensions": [".scss", ".whatever"]
}
```

**Comment by hoest** [comment]
Are both settings required? If I only add `extensions` to my settings-file, it won't work...

**Comment by dmnsgn** [comment]
The `syntaxes` are checked first, then the `extensions`. If your file has one or the other, it should work. Is "formatOnSave" set to `true`?

The following `name.sublime-project` works for me (on save of a `.scss` file, it gets formatted):
```json
{
	"folders":
	[
		{
			"path": "."
		}
	],
	"settings":
	{
		"Stylefmt": {
			"formatOnSave": true,
			"syntaxes": ["SCSS"],
			"extensions": [".scss"]
		}
	}
}
```

**Comment by hoest** [comment]
Yes, this also works for me, but I thought it would be possible to set only the `extensions` property, like this:

```
	...
	"settings" : {
		"Stylefmt": {
			"formatOnSave": true,
			"extensions": [".scss"]
		}
	}
	...
```
