### ISSUE TITLE
Stylus support

### ISSUE THREAD

**Issue by prorockdesign** [dmnsgn/sublime-stylefmt#22]
Hi. How can I configure Stylefmt to work with Stylus?

`{
  "formatOnSave": false,
  "syntaxes": ["Stylus"],
  "extensions": [".styl"]
}
`

It's doesn't work.

**Comment by dmnsgn** [comment]
Stylefmt is using `postcss` and I am not sure it understands the stylus syntax.

Anyway if you want the file to be formatted on save, you should set "formatOnSave" to true:
```json
{
  "formatOnSave": true,
  "syntaxes": ["SCSS", "ASyntaxThatPostCssUnderstand"],
  "extensions": [".scss"]
}
```

**Comment by prorockdesign** [comment]
Thanks. Too bad that it doesn't support stylus syntax.
