### ISSUE TITLE
Update to latest stylelint

### ISSUE THREAD

**Issue by ronilaukkarinen** [dmnsgn/sublime-stylefmt#26]
Hello! Old stylelint in node_modules causes problems like [this](https://github.com/morishitter/stylefmt/issues/334). The only way to fix this currently is to overwrite stylelint with node_modules directory.

**Comment by dmnsgn** [comment]
Stylelint is a dependency of `stylefmt`, it is not directly coming from `sublime-stylefmt`: https://github.com/morishitter/stylefmt/blob/master/package.json#L44

You should probably mention this issue on `stylefmt` repo.

**Comment by ronilaukkarinen** [comment]
Yeah, it's mentioned there already, but I just wanted to clarify this, because it's confusing. Can't stylelint subdir be updated to the repo in the meantime, [here](https://github.com/dmnsgn/sublime-stylefmt/tree/master/node_modules/stylelint)?

**Comment by dmnsgn** [comment]
9dd04c9 adds support for stylefmt cli arguments (config, config-basedir, ignore-path).

NB: stylefmt most likely won't get any updates anymore as `stylelint's --fix` is recommended
