### ISSUE TITLE
.editorconfig settings not picked up 

### ISSUE THREAD

**Issue by dmnsgn** [dmnsgn/sublime-stylefmt#7]
The cwd is probably wrong

**Comment by gucong3000** [comment]
https://github.com/morishitter/stylefmt/issues/220

**Comment by gucong3000** [comment]
Test OK in PR #18 
But please note:
All stylelint configuration files must be deleted, then .editorconfig settings can picked up.
This is @morishitter 's hope. see: https://github.com/morishitter/stylefmt/pull/221#issuecomment-254443211
