### ISSUE TITLE
stylefmt cannot find Node.js with nvm in Sublime Text

### ISSUE THREAD

**Issue by morishitter** [dmnsgn/sublime-stylefmt#9]
Do you have any ideas about this issue? https://github.com/morishitter/stylefmt/issues/91

Thanks.

**Comment by dmnsgn** [comment]
Have you tried to symlink the node version installed by nvm ?
`ln -s /path/to/nvm/node /usr/local/bin/node`

**Comment by dmnsgn** [comment]
Thanks @DylanPiercey ! Let us know if you find out what was wrong on your first computer.
